In [42]:
# Import necessary libraries
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
import xgboost as xgb
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.ensemble import RandomForestRegressor

In [13]:
# Load the dataset
df= pd.read_csv("H:\\Guvi\\Project\\Final project\\Project 2 (Rating of udemy courses)\\3.1-data-sheet-udemy-courses.csv")
df

,course_id,course_title,url,price,num_subscribers,num_reviews,num_lectures,level,Rating,content_duration,published_timestamp,subject
0,41295.0,Learn HTML5 Programming From Scratch,https://www.udemy.com/learn-html5-programming-...,0.0,268923.0,8629.0,45.0,Beginner Level,0.82,10.500000,2013-02-14T07:03:41Z,Subject: Web Development
1,59014.0,Coding for Entrepreneurs Basic,https://www.udemy.com/coding-for-entrepreneurs...,0.0,161029.0,279.0,27.0,Expert Level,0.69,3.500000,2013-06-09T15:51:55Z,Subject: Web Development
2,625204.0,The Web Developer Bootcamp,https://www.udemy.com/the-web-developer-bootcamp/,200.0,121584.0,27445.0,342.0,Beginner Level,0.89,43.000000,2015-11-02T21:13:27Z,Subject: Web Development
3,173548.0,Build Your First Website in 1 Week with HTML5 ...,https://www.udemy.com/build-your-first-website...,0.0,120291.0,5924.0,30.0,All Levels,0.78,3.000000,2014-04-08T16:21:30Z,Subject: Web Development
4,764164.0,The Complete Web Developer Course 2.0,https://www.udemy.com/the-complete-web-develop...,200.0,114512.0,22412.0,304.0,Beginner Level,0.55,30.500000,2016-03-08T22:28:36Z,Subject: Web Development
...,...,...,...,...,...,...,...,...,...,...,...,...
3675,1216340.0,Learn to Play Sweet Child of Mine,https://www.udemy.com/learn-to-play-sweet-chil...,20.0,0.0,0.0,23.0,All Levels,0.31,1.500000,2017-06-30T17:33:29Z,Musical Instruments
3676,1026762.0,Coaching Course: Rhythm Instruction for Music ...,https://www.udemy.com/coaching-bundle-rhythm-i...,125.0,0.0,0.0,7.0,Beginner Level,0.06,0.633333,2017-03-10T17:06:46Z,Musical Instruments
3677,1223240.0,Learn Pirates of the Caribbean by Ear on the P...,https://www.udemy.com/learn-pirates-of-the-car...,20.0,0.0,0.0,6.0,All Levels,0.08,0.533333,2017-05-22T17:14:43Z,Musical Instruments
3678,1224186.0,Learn to Play Piano Like a Pro - Easy Piano Co...,https://www.udemy.com/learn-to-play-piano-like...,35.0,0.0,0.0,13.0,Beginner Level,0.78,0.516667,2017-05-30T00:19:02Z,Musical Instruments
3679,1234656.0,4 Week Rhythm Mastery,https://www.udemy.com/4-week-rhythm-mastery/,20.0,0.0,0.0,28.0,All Levels,0.01,2.500000,2017-07-05T16:07:44Z,Musical Instruments

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3680 entries, 0 to 3679
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   course_id            3676 non-null   float64
 1   course_title         3676 non-null   object
 2   url                  3676 non-null   object
 3   price                3676 non-null   float64
 4   num_subscribers      3676 non-null   float64
 5   num_reviews          3676 non-null   float64
 6   num_lectures         3676 non-null   float64
 7   level                3676 non-null   object
 8   Rating               3676 non-null   float64
 9   content_duration     3676 non-null   float64
 10  published_timestamp  3676 non-null   object
 11  subject              3677 non-null   object
dtypes: float64(7), object(5)
memory usage: 345.1+ KB

In [15]:
df.isna().sum()

course_id              4
course_title           4
url                    4
price                  4
num_subscribers        4
num_reviews            4
num_lectures           4
level                  4
Rating                 4
content_duration       4
published_timestamp    4
subject                3
dtype: int64

In [16]:
df.shape

(3680, 12)

In [17]:
# Drop unnecessary columns (assuming 'course_id' and 'url' are not relevant for the prediction)
df = df.drop(["course_id", "url", "published_timestamp"], axis=1)

In [18]:
# Perform data cleaning (handling missing values)
df = df.dropna()  # Drop rows with missing values

In [19]:
df.isna().sum()

course_title        0
price               0
num_subscribers     0
num_reviews         0
num_lectures        0
level               0
Rating              0
content_duration    0
subject             0
dtype: int64

In [27]:
# Encode the course_title column using label encoding
label_encoder = LabelEncoder()
df["course_title_encoded"] = label_encoder.fit_transform(df["course_title"])

In [51]:
df.head()

,course_title,price,num_subscribers,num_reviews,num_lectures,Rating,content_duration,level_All Levels,level_Beginner Level,level_Expert Level,level_Intermediate Level,subject_Business Finance,subject_Graphic Design,subject_Musical Instruments,subject_Subject: Web Development,course_title_encoded
0,Learn HTML5 Programming From Scratch,0.0,268923.0,8629.0,45.0,0.82,10.5,False,True,False,False,False,False,False,True,2108
1,Coding for Entrepreneurs Basic,0.0,161029.0,279.0,27.0,0.69,3.5,False,False,True,False,False,False,False,True,755
2,The Web Developer Bootcamp,200.0,121584.0,27445.0,342.0,0.89,43.0,False,True,False,False,False,False,False,True,3296
3,Build Your First Website in 1 Week with HTML5 ...,0.0,120291.0,5924.0,30.0,0.78,3.0,True,False,False,False,False,False,False,True,590
4,The Complete Web Developer Course 2.0,200.0,114512.0,22412.0,304.0,0.55,30.5,False,True,False,False,False,False,False,True,3227

In [45]:
# Split the dataset into training and testing sets
X = df.drop(["Rating", "course_title"], axis=1)
y = df["Rating"]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [46]:
# Perform feature scaling
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [47]:
# Train the regression model (XGBoost)
model = xgb.XGBRegressor()
model.fit(X_train_scaled, y_train)

# Evaluate the model
y_pred = model.predict(X_test_scaled)
mse = mean_squared_error(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error (MSE):", mse)
print("Mean Absolute Error (MAE):", mae)
print("R-squared Score:", r2)

Mean Squared Error (MSE): 0.07767542185866919
Mean Absolute Error (MAE): 0.21648386213653825
R-squared Score: 0.29376471442152585